<a href="https://colab.research.google.com/github/yemanzhongting/MultiCity/blob/main/%E8%BE%93%E5%87%BA%E5%AD%97%E5%90%91%E9%87%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install transformers

     |████████████████████████████████| 2.6 MB 5.0 MB/s 
     |████████████████████████████████| 895 kB 47.6 MB/s 
     |████████████████████████████████| 3.3 MB 44.6 MB/s 
     |████████████████████████████████| 636 kB 46.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("ethanyt/guwenbert-base")

model = AutoModel.from_pretrained("ethanyt/guwenbert-base")

Downloading:   0%|          | 0.00/519 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/93.5k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/418M [00:00<?, ?B/s]

Some weights of the model checkpoint at ethanyt/guwenbert-base were not used when initializing RobertaModel: ['lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.decoder.bias', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [4]:
import torch

In [16]:
input_ids=torch.tensor(tokenizer.encode("我爱喵喵哈哈")).unsqueeze(0)

In [17]:
input_ids

tensor([[    0,    97,   597, 21117, 21117,  1572,  1572,     2]])

In [18]:
output=model(input_ids)

In [19]:
# output

In [20]:
sequence_output=output[0]

In [21]:
pooled_output=output[1]

In [22]:
##输出单词向量
sequence_output

tensor([[[-0.0364, -0.0408, -0.1119,  ..., -0.0235, -0.0356,  0.0215],
         [ 0.1632, -0.0586, -0.1037,  ...,  0.1123, -0.0552,  0.0053],
         [ 0.0746,  0.0540, -0.1666,  ...,  0.0157, -0.0587,  0.0317],
         ...,
         [ 0.1804, -0.0677, -0.2322,  ...,  0.1561, -0.0610,  0.0555],
         [ 0.2077, -0.0290, -0.2602,  ...,  0.1300, -0.0548,  0.0806],
         [ 0.1602,  0.0786, -0.1318,  ...,  0.1721, -0.2063,  0.1287]]],
       grad_fn=<NativeLayerNormBackward>)

In [24]:
sequence_output.shape
#对应的8个单词 有开始结尾的标签向量
# [    0,    97,   597, 21117, 21117,  1572,  1572,     2]

torch.Size([1, 8, 768])

In [27]:
##以下额外知识，可以不看

In [30]:
##输出句子向量,隐藏状态在模型的最后一层输出
pooled_output.shape

torch.Size([1, 768])

In [29]:
output

BaseModelOutputWithPoolingAndCrossAttentions([('last_hidden_state',
                                               tensor([[[-0.0364, -0.0408, -0.1119,  ..., -0.0235, -0.0356,  0.0215],
                                                        [ 0.1632, -0.0586, -0.1037,  ...,  0.1123, -0.0552,  0.0053],
                                                        [ 0.0746,  0.0540, -0.1666,  ...,  0.0157, -0.0587,  0.0317],
                                                        ...,
                                                        [ 0.1804, -0.0677, -0.2322,  ...,  0.1561, -0.0610,  0.0555],
                                                        [ 0.2077, -0.0290, -0.2602,  ...,  0.1300, -0.0548,  0.0806],
                                                        [ 0.1602,  0.0786, -0.1318,  ...,  0.1721, -0.2063,  0.1287]]],
                                                      grad_fn=<NativeLayerNormBackward>)),
                                              ('pooler_output',
      